(include_subdirs no)

(library
 (name storage_melange)
 (public_name datascript-ocaml-melange.storage)
 (wrapped false)
 (modes melange)
 (modules
  datascript_storage_meta
  datascript_storage_lmdb
  datascript_storage_protocol)
 (libraries datascript_lmdb_codec lmdb_db_melange lmdb_index_melange datascript_types))
