(include_subdirs no)

(library
 (name storage_native)
 (public_name datascript-ocaml-native.storage)
 (wrapped false)
 (modes native)
 (modules
  datascript_storage_meta
  datascript_storage_lmdb
  datascript_storage_protocol)
 (libraries
  datascript_ocaml.index-codec
  lmdb_db_native
  lmdb_index_native
  sqlite_db_native
  datascript_types))
