opam-version: "2.0"
synopsis: "js_of_ocaml implementation for DataScript OCaml"
description: "js_of_ocaml implementation package for the DataScript OCaml virtual library."
maintainer: "rcmerci"
authors: ["rcmerci"]
license: "MIT"
depends: [
  "ocaml" {>= "5.1.1"}
  "dune" {>= "3.17"}
  "datascript_ocaml" {= version}
  "js_of_ocaml"
]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
