opam-version: "2.0"
synopsis: "An OCaml 5 rewrite of DataScript"
description: "A OCaml 5 rewrite of DataScript."
maintainer: "rcmerci"
authors: ["rcmerci"]
license: "MIT"
depends: [
  "ocaml" {>= "5.1.1"}
  "dune" {>= "3.17"}
  "persistent_sorted_set_ocaml" {= "dev"}
  "melange"
  "odoc" {with-doc}
]
pin-depends: [
  ["persistent_sorted_set_ocaml.dev" "git+https://github.com/logseq/persistent-sorted-set-ocaml.git#b4c97e37b4d62175b376d76e795c298071444343"]
]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
