opam-version: "2.0"
synopsis: "LMDB persistent storage for DataScript OCaml"
description: "File-backed LMDB storage sessions for datascript-ocaml-native."
maintainer: "rcmerci"
authors: ["rcmerci"]
license: "MIT"
depends: [
  "ocaml" {>= "5.1.1"}
  "dune" {>= "3.17"}
  "datascript-ocaml-native" {= version}
  "lmdb"
]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
