(library
 (name datascript_sqlite)
 (public_name datascript-ocaml-native.sqlite)
 (wrapped false)
 (foreign_stubs
  (language c)
  (names datascript_sqlite_stubs))
 (c_library_flags
  (:standard -L%{env:DATASCRIPT_SQLITE_LIB_DIR=.} -lsqlite3))
 (libraries datascript-ocaml-native persistent_sorted_set_ocaml melange-transit-native))
