(include_subdirs no)

(library
 (name lmdb_db_native)
 (public_name datascript-ocaml-native.lmdb-db)
 (wrapped false)
 (modes native)
 (modules datascript_lmdb_db)
 (libraries datascript_lmdb_codec lmdb))

(library
 (name lmdb_index_native)
 (public_name datascript-ocaml-native.lmdb-index)
 (wrapped false)
 (modes native)
 (modules datascript_lmdb_index)
 (libraries datascript_lmdb_codec lmdb_db_native))

(library
 (name storage_lmdb_native)
 (public_name datascript-ocaml-native.storage-lmdb)
 (wrapped false)
 (modes native)
 (modules datascript_storage_lmdb)
 (libraries datascript_lmdb_codec lmdb_db_native datascript_types))
